api_platform:
    title: 'Bastide API'
    version: '1.0.0'
    formats:
        jsonld:  ['application/ld+json']
        json:    ['application/json']
        html:    ['text/html']
    docs_formats:
        json:    ['application/json']
        jsonld:  ['application/ld+json']
        html:    ['text/html']
        yaml:    ['application/x-yaml']
