nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: []
        max_age: 3600

    paths:
        '^/':
            allow_origin: [
                'https://bastide.tn',
                'https://www.bastide.tn',
                'https://bastide.com.tn',
                'https://www.bastide.com.tn',
                'https://api.bastide.com.tn',
                'http://localhost:5173',
                'http://127.0.0.1:5173'
            ]
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_credentials: true
            max_age: 3600
